### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by 0xCowz** [dawg1337/FiveM_Naloxone#2]
1 second after injection, the game is just crashing without any errors.

**Comment by ghost** [comment]
Due this shit ain't working with adhesive since whole lua scripting is moved there also even if you fixed this shit for adhesive integrity would fuck you up.

**Comment by 0xCowz** [comment]
> Due this shit ain't working with adhesive since whole lua scripting is moved there also even if you fixed this shit for adhesive integrity would fuck you up.

ok ok
